version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://db:27017/booksmongodb


  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"













